#5 Add more descriptive output to bash script

diff --git a/public/bash.template b/public/bash.template
--- a/public/bash.template
+++ b/public/bash.template
@@ -12,17 +12,37 @@ format="tarpaulin"
 report=""
 token="$COV_TOKEN"
 
-if [[ "$CI" == "drone" ]]; then
+function verbose_say() {
+  if [ -z "$QUIET" ] || [ "$VERBOSE" == "true" ]; then
+    echo "$1"
+  fi
+}
+
+verbose_say "==========================="
+verbose_say "        ao-coverage        "
+verbose_say "==========================="
+verbose_say
+
+verbose_say "Gathering report information . . ."
+
+if [ "$CI" == "drone" ]; then
+  verbose_say "Drone CI discovered - using Drone report info"
   commit="$DRONE_COMMIT"
   branch="$DRONE_BRANCH"
   repo="$DRONE_REPO"
 else
+  verbose_say "Using environment variables for report info"
   commit="$VCS_COMMIT"
   branch="$VCS_BRANCH"
   repo="$VCS_REPO"
 fi
 
-if [[ "$format" == "tarpaulin" ]]; then
+verbose_say "Using commit #: $commit"
+verbose_say "Using branch: $branch"
+verbose_say "Using repo: $repo"
+verbose_say
+
+if [ "$format" == "tarpaulin" ]; then
   report="${REPORT_FILE:-tarpaulin-report.html}"
 fi
 
@@ -31,4 +51,22 @@ if [[ ! -f "$report" ]]; then
   exit 1
 fi
 
-curl -X POST --data-binary "@$report" -H 'Content-Type: text/html' "$url/v1/$repo/$branch/$commit.html?token=$token&format=tarpaulin"
+verbose_say "Uploading $report . . ."
+
+response=$(curl -X POST --data-binary "@$report" \
+  -H 'Content-Type: text/html' \
+  "$url/v1/$repo/$branch/$commit.html?token=$token&format=$format")
+
+if [ ! -z "$response" ]; then
+  echo "Error uploading report: $response"
+  exit 1
+else
+  echo "Successfully uploaded report!"
+  verbose_say
+  verbose_say "View uploaded report at: $url/v1/$repo/$branch/$commit.html"
+  verbose_say "View coverage badge at: $url/v1/$repo/$branch/$commit.svg"
+  verbose_say
+  verbose_say "Shorthand links are also available, as the latest commit of this branch."
+  verbose_say "View latest report for branch $branch: $url/v1/$repo/$branch.html"
+  verbose_say "View latest badge for branch $branch: $url/v1/$repo/$branch.svg"
+fi
